  env:
      u2AuthorizeUrl: A
      u2AccessTokenUrl: V
      u2LogoutUrl: XXX
      clientId: 9688
      clientSecret: u2test-bd848c88-4b2e-4209-b228-47e33da8fa5c
      callbackUrl: sss
      logoffCallbackUrl: /exit.jsp
      u2ApiUrl: AA
      u2LoginUrl: ss
      u2AppID: 90101
      u2AppKey: ss#$vs
      baseUrl: AA
      domain: AA