spring:
  mvc:
    view:
      prefix: /WEB-INF/web/
      suffix: .jsp
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 2000MB
      max-request-size: 2000MB
logging:
  config: classpath:logback.xml
  path: /data/logs

mybatis:
  mapperLocations: classpath:/com/xdf/example/mapper/*.xml
  typeAliasesPackage: com.xdf.example.mapper
  mapperScanPackage: com.xdf.example.mapper
  configLocation: classpath:/mybatis-config.xml

oracle:
  datasource:
    readSize: 2
    type: com.alibaba.druid.pool.DruidDataSource
    mapperLocations: classpath:/com/xdf/example/mapper/*.xml
    configLocation: classpath:/mybatis-config.xml
    write:
      url: jdbc:mysql://10.200.116.82/globalyou
      username: root
      password: password
      driver-class-name: com.mysql.jdbc.Driver
    read01:
      url: jdbc:mysql://10.200.116.82/globalyou
      username: root
      password: password
      driver-class-name: com.mysql.jdbc.Driver
    read02:
      url: jdbc:mysql://10.200.116.82/globalyou
      username: root
      password: password
      driver-class-name: com.mysql.jdbc.Driver
server:
  port: 80
